### ISSUE TITLE
Markel do you have youtube videos for the content of this repo?

### ISSUE THREAD

**Issue by hansschenker** [mtuzinskiy/learning#26]
you are an expert in functional programming. It would be very helpful if you had videos on this content! You should even consider to sell your videos on udemy.com, scrimba.com or educative.io!
Thank's a lot
Hans
calling from Switzerland

**Comment by mtuzinskiy** [comment]
Hi Hans!
Thanks for your warm feedback, I appreciate it!

These are the supplementary materials for the trainings that I do internally for my company.
However, there are 2 of them that are publicly available on Youtube:
https://www.youtube.com/watch?v=YWWsxKAQb6s  (FP introduction for frontend developers)
https://www.youtube.com/watch?v=6nayX_fqWb4  (FRP introduction, I'm showing the snake game written in RxJS. Code is also publicly available [here](https://github.com/mtuzinskiy/frp-snake))
They cover all the basics + some advanced topics, have a look :slightly_smiling_face: 

I thought about running my own Youtube channel dedicated to web UI, but I simply don't have enough of spare time for now...
Thanks again!

Markel
